### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by aznyqjai** [aznyqjai/midlife#2]
Design

**Comment by iveygtaylor** [comment]
Hey!
@aznyqjai 
@joey-vito 
Here is my first pass at the 
![mid-life crisis coders](https://cloud.githubusercontent.com/assets/22942861/19570370/b74f16ce-96c7-11e6-8601-db5ec08f9163.png)

**Comment by iveygtaylor** [comment]
How about this?
@aznyqjai 
@joey-vito 
![mid-life crisis coders 1](https://cloud.githubusercontent.com/assets/22942861/19570959/20944a26-96ca-11e6-9a91-4b793f2bd87b.png)

**Comment by iveygtaylor** [comment]
How about this to use for the logo in the upper left corner of each page? 
@aznyqjai 
@joey-vito 
![mid-life crisis coders logo](https://cloud.githubusercontent.com/assets/22942861/19573306/c5c7bfc4-96d3-11e6-9d13-37315f34f48f.png)

**Comment by shawnwildo** [comment]
Image header approved and ready to go!
