### ISSUE TITLE
Create a contact submission form

### ISSUE THREAD

**Issue by shawnwildo** [aznyqjai/midlife#6]
Create a contact submission form and have it alert the user with "Thanks for contacting us" pop up on the page afterwards.

**Comment by shawnwildo** [comment]
Hey Q,for some reason neither Ryan nor Paul received their invitations to collaborate on the project. Can you re-add them please? Thanks!

**Comment by aznyqjai** [comment]
ryan is in, paul's got the invite.
contact form is there now, not much functioning though
